stages:
  - static_tests
  - dynamic_tests
  - build
  - release

# Doc : https://r2devops.io/jobs/
include:
  #- remote: https://jobs.r2devops.io/gitleaks.yml
  # - remote: https://jobs.r2devops.io/sls_scan.yml
  - remote: https://jobs.r2devops.io/docker_build.yml
  # - remote: https://jobs.r2devops.io/trivy_image.yml

# frontend
docker_build:
  variables:
    DOCKER_CONTEXT_PATH: './front/'
    DOCKER_USE_CACHE: 'true'
    DOCKERFILE_PATH: './Dockerfile'

# backend
docker_build_backend:
  stage: build
  extends: docker_build
  variables:
    DOCKER_CONTEXT_PATH: './backend/'
    DOCKER_USE_CACHE: 'true'
    DOCKERFILE_PATH: './Dockerfile'
