stages:
  - 📦build
  - 🦄tmp
  - static_tests
  - build
  - dynamic_tests
  - release
image: asciidoctor/docker-asciidoctor:1.16

pdf_preview:
  stage: 🦄tmp
  when: manual
  environment:
    name: preview/$CI_COMMIT_REF_NAME
  except:
    - /master/
  artifacts:
    paths:
      - index.pdf
    expire_in: 1 week
  script:
    - asciidoctor-pdf -a pdf-style=./doc/assets/book.yml -a pdf-fontsdir=./doc/assets/fonts doc/index.adoc
pdf_publication:
  stage: 📦build
  environment:
    name: production
  only:
    - /master/
  artifacts:
    paths:
      - index.pdf
    expire_in: 1 week
  script:
    - asciidoctor-pdf -a pdf-style=./doc/assets/book.yml -a pdf-fontsdir=./doc/assets/fonts doc/index.adoc

# Doc : https://r2devops.io/jobs/
include:
  - remote: https://jobs.r2devops.io/gitleaks.yml
  # - remote: https://jobs.r2devops.io/sls_scan.yml
  - remote: https://jobs.r2devops.io/docker_build.yml
  # - remote: https://jobs.r2devops.io/trivy_image.yml
#frontend
docker_build:
  variables:
    DOCKER_CONTEXT_PATH: "./front"
    DOCKER_USE_CACHE: "true"

docker_build_backend:
  extends: docker_build
  variables:
    DOCKER_CONTEXT_PATH: "./backend/api"
    DOCKER_USE_CACHE: "true"
