stages:
  - static_tests
  - dynamic_tests
  - build
  - release
  - deploy

# Doc : https://r2devops.io/jobs/
include:
  #- remote: https://jobs.r2devops.io/gitleaks.yml
  # - remote: https://jobs.r2devops.io/sls_scan.yml
  - remote: https://jobs.r2devops.io/docker_build.yml
  # - remote: https://jobs.r2devops.io/trivy_image.yml

# frontend
docker_build:
  variables:
    DOCKER_CONTEXT_PATH: './front/'
    DOCKER_USE_CACHE: 'true'
    DOCKERFILE_PATH: './Dockerfile'
    TAG_CREATE_LATEST: 'true'

# backend
docker_build_backend:
  stage: build
  extends: docker_build
  variables:
    DOCKER_CONTEXT_PATH: './backend/'
    DOCKER_USE_CACHE: 'true'
    DOCKERFILE_PATH: './Dockerfile'
    TAG_CREATE_LATEST: 'true'

# documentation
build:
  image: debian:bullseye-slim
  stage: build
  environment:
    name: production
  artifacts:
    paths:
      - doc/index.pdf
    expire_in: 1 week
  script:
    - apt update
    - apt install -y build-essential
    - make setup
    - make build

deploy_dev:
  stage: deploy
  only:
    - main
  script:
    - apt update -y
    - apt install -y openssh-client
    - eval $(ssh-agent)
    - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d | tr -d '\r')
    #- ssh $SSH_USER@$SSH_HOST -p $SSH_PORT -o LogLevel=ERROR "mkdir -p /opt/polytrade"
    #- scp -q -r -P $SSH_PORT . $SSH_USER@$SSH_HOST:/opt/polycloud/
    - ssh $SSH_USER@$SSH_HOST -o StrictHostKeyChecking=no -o LogLevel=ERROR "cd /opt/polytrade && docker-compose pull && docker-compose up -d --remove-orphans"
  environment:
    name: dev
    url: https://polytrade.cluster-2020-11.dopolytech.fr/
