version: "3.8"

services:
  front:
    image: TODO
    ports:
      - 80:80
    volumes:
      - ./assets/config.js:/usr/share/nginx/html/assets/config.js
    environment:
      NODE_ENV: production
      PORT: 80
      HOST: http://localhost
      API_HOST: http://localhost:81
    networks:
      - frontend
  api:
    image: TODO
    ports:
      - 81:80
    networks:
      - frontend
      - backend
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: polytrade
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodata:/data/db
    networks:
      - backend
volumes:
  mongodata:

networks:
  frontend:
  backend: