version: "3.8"

services:
  front:
    container_name: poly-trade-front
    build: ./front/
    ports:
      - 80:80
    environment:
      NODE_ENV: production
    networks:
      - frontend
  api:
    container_name: poly-trade-api
    build: ./backend/
    ports:
      - 81:80
    networks:
      - frontend
      - backend
    environment:
      HTTP_HOST: http://127.0.0.1
      HTTP_PORT: 80
      DATABASE_URL: mongodb://root:root@poly-trade-mongodb:27017/polytrade
  mongodb:
    container_name: poly-trade-mongodb
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: polytrade
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodata:/data/db
    networks:
      - backend
volumes:
  mongodata:

networks:
  frontend:
  backend: